### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by Baltazar95** [AntonioCPacheco/ShatteredGame#12]
Create:
- Start Menu;
- Pause Menu, with sound options(To be specified) and Restart;

**Comment by AfonsoCR** [comment]
I will create:

- The sounds for menu open, menu scroll, menu select, menu return, slider movement and menu out;

- A pause game event, in which all sounds except for the menu sounds (and possibly menu music) will be paused;

- A leave pause game event, in which it resumes all the previously paused sounds;

- Events for scrolling, selecting, slider sounds and returning;

- A game parameter for each of these sliders and adjust their range from 0-100, with 100 being the default;
These parameters will be linked to the various audio busses, allowing for the sound to be automatically adjusted when the slider is moved.

In Game Maker, in addition to any other possible game options, create an 'Audio' tab with 3 sliders - Master Volume, Music Volume, SFX Volume; 
These will have to be linked to the game parameters and to their respective game events (slider sound event).

**Comment by Baltazar95** [comment]
in Start Menu:

- choice between the two levels;

- options;

- exit;

in Pause Menu:

- resume;

- options;

- exit;

**Comment by Baltazar95** [comment]
not functional
